INSERT INTO page(title, content) VALUES ('A title', 'A content');
INSERT INTO page(title, content, parent_id) VALUES ('B title', 'B content', 1);
INSERT INTO page(title, content, parent_id) VALUES ('C title', 'C content', 2);
INSERT INTO page(title, content, parent_id) VALUES ('D title', 'D content', 3);
INSERT INTO page(title, content, parent_id) VALUES ('E title', 'E content', 4);
INSERT INTO page(title, content, parent_id) VALUES ('F title', 'F content', 5);
INSERT INTO page(title, content, parent_id) VALUES ('G title', 'G content', 6);
INSERT INTO page(title, content, parent_id) VALUES ('H title', 'H content', 7);
INSERT INTO page(title, content, parent_id) VALUES ('I title', 'I content', 8);
INSERT INTO page(title, content, parent_id) VALUES ('J title', 'J content', 9);
INSERT INTO page(title, content, parent_id) VALUES ('K title', 'K content', 9);
INSERT INTO page(title, content, parent_id) VALUES ('L title', 'L content', 9);