DROP TABLE IF EXISTS page;

CREATE TABLE page
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     CHARACTER VARYING,
    content   CHARACTER VARYING,
    parent_id BIGINT,
    FOREIGN KEY (parent_id) REFERENCES page (id)
);
CREATE INDEX page_by_parent_id ON page (parent_id);
